version: "3"
services:
  voting-app:
    image: voting-app
    ports:
      - 5000:80
    networks: 
      - front-end
      - back-end
    depends_on:
      - redis
  redis:
    image: redis:5.0-alpine3.10 
    networks: 
      - back-end

  worker:
    image: worker
    networks:
      - back-end
  db:
    image: postgres:9.4
    networks:
      - back-end
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  result-app:
    image: result-app
    ports:
      - 5001:80
    networks:
      - front-end
      - back-end
networks:
  front-end:
  back-end:
